Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: helloworld.user.create.CreateUserHandler
      CodeUri: /Users/kyungsoolee/GitRepositories/LambdaStudy/HelloWorldFunction
      Runtime: java17
      Architectures:
        - x86_64